run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Disable field alignment checks - too noisy for struct optimization
      - shadow         # Disable shadow variable checks - often false positives in test contexts
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - checkPrivateReceivers
  gocyclo:
    min-complexity: 40
  dupl:
    threshold: 100
  goconst:
    min-len: 3          # Increased from 2 to reduce noise
    min-occurrences: 5  # Increased from 2 to only catch significant repetitions
  misspell:
    locale: US
  lll:
    line-length: 160
  goimports:
    local-prefixes: github.com/ginsys/forward-email
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
      - exitAfterDefer
      - paramTypeCombine
      - rangeValCopy
      - appendAssign
      - dupBranchBody
      - emptyStringTest
      - equalFold
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/ginsys/forward-email
          - github.com/spf13/cobra
          - github.com/spf13/viper
          - github.com/99designs/keyring
          - github.com/olekukonko/tablewriter
          - golang.org/x/term
          - gopkg.in/yaml.v3
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Should be replaced by standard lib errors package"

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    # - dupl          # disabled: too noisy, prefer targeted refactors
    - errcheck
    - exhaustive
    # - goconst       # disabled: too noisy for test files, causes CI noise
    - gocritic
    # - gocyclo       # disabled: complexity thresholds enforced via reviews
    - gofmt
    - goimports
    - revive
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    # - unparam       # disabled: too noisy, especially in test helper functions
    - unused
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Relax linting standards for test files
    - path: _test\.go
      linters:
        - mnd
        - goconst        # Allow string repetition in tests
        - gosec          # Allow security relaxations in tests
        - unparam        # Allow unused parameters in test helpers
        - lll            # Allow longer lines in test cases
        - dupl           # Allow duplication in test setup
        - shadow         # Allow shadow variables in test scopes
        - revive         # Relax style checks in tests
        - misspell       # Allow common test misspellings
        - govet          # Relax vet checks in tests
        - staticcheck    # Relax static analysis in tests
        - stylecheck     # Relax style requirements in tests

    # Disable errcheck entirely for test files
    - path: _test\.go
      linters:
        - errcheck

    # Allow gocritic httpNoBody suggestions in tests
    - path: _test\.go
      linters:
        - gocritic
      text: 'httpNoBody'
    
    # Allow standard library imports everywhere
    - linters:
        - depguard
      text: "import .* is not allowed from list 'main'"
      source: "^import \"(context|fmt|os|syscall|time|net/|encoding/|path/|runtime)\""

    # Allow constant suggestions in error mapping file
    - path: pkg/errors/errors\.go
      linters:
        - goconst
    
    # Allow magic numbers in configuration defaults
    - path: config\.go
      linters:
        - mnd
    
    # Allow stuttering in API package names
    - linters:
        - revive
      text: "stutters"
    
    # Allow fieldalignment in CLI profile struct declarations
    - path: internal/cmd/profile\.go
      linters:
        - govet
      text: "fieldalignment:"
    
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    
    # Global exclusions for common patterns
    # Allow HTTP method constants in tests - these are standard patterns
    - text: 'string `(GET|POST|PUT|DELETE)` has .* occurrences, make it a constant'
      linters:
        - goconst
    
    # Allow common test data repetition
    - text: 'string `(test|example\.com|localhost)` has .* occurrences, make it a constant'
      linters:
        - goconst
    
    # Allow unused name parameter in helper functions (common pattern)
    - text: '`\w+` - `name` is unused'
      linters:
        - unparam
    
    # Allow field alignment in API structures (performance vs readability tradeoff)
    - text: 'fieldalignment: struct with .* pointer bytes could be'
      linters:
        - govet
      path: 'pkg/api/.*\.go$'
