project_name: forward-email
before:
  hooks:
    - go mod tidy
builds:
  - id: forward-email
    main: ./cmd/forward-email
    ldflags:
      - -X github.com/ginsys/forward-email/internal/version.Version={{.Version}}
      - -X github.com/ginsys/forward-email/internal/version.Commit={{.ShortCommit}}
      - -X github.com/ginsys/forward-email/internal/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
archives:
  - id: archive
    builds: [forward-email]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
release:
  github:
    owner: ginsys
    name: forward-email
  draft: false
  prerelease: auto
changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
